### ISSUE TITLE
Cache Resolved Bindings

### ISSUE THREAD

**Issue by douglascayers** [apex-enterprise-patterns/force-di#13]
Support caching support to improve performance of resolving bindings, particularly when there are dozens to hundreds and the bindings do complex processing.

Subscriber would provide a platform cache name for a partition they make available for this purpose. This will need a new setting somewhere to capture this.

Two main points where to utilize caching:
* Binding.Resolver.get() method 
* Injector.CustomMetadataModule

Cache keys should be the unique name for the binding, and this requires code changes to ensure bindings have a unique name regardless where they are created from (custom metadata or programmatically).

**Comment by afawcett** [comment]
@ImJohnMDaniel @douglascayers whats the status on this?

**Comment by ImJohnMDaniel** [comment]
This has actually been completed.  Force-DI now supports platform cache.

This issue can be closed.
